name: firebase_dashboard
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: 
  sweetsheet: any
  flutter_spinbox:
  firebase_core: any
  firebase_storage: any
  firebase_auth: any
  cloud_firestore:    

  get:
  get_storage:
  
  awesome_extensions:
  
  uuid: any  
  badges:
  multi_select_flutter:
  multiselect: any
  flutter_tags: 
  #flutter_typeahead: 

  #syncfusion_flutter_xlsio:
  syncfusion_flutter_datagrid_export: 
  syncfusion_flutter_datagrid: 
  syncfusion_localizations:
  syncfusion_flutter_xlsio: 
  
  image_picker:
  dropdown_button2: 
  textfield_tags:
  file_selector:

  filesize:
  download:
  url_launcher:
  super_tag_editor:
  flutter_colorpicker:
  anim_search_bar:
  app_bar_with_search_switch:
  cached_network_image:
  flex_color_scheme:


  settings_ui:

  event_bus:

flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
